apiVersion: projectcalico.org/v4
kind: BGPConfiguration
metadata:
  name: default
spec:
  logSeverityScreen: Info
  nodeToNodeMeshEnabled: true
  asNumber: 64512
---
apiVersion: projectcalico.org/v4
kind: BGPPeer
metadata:
  name: nginx-lb
spec:
  peerIP: 172.16.20.15
  asNumber: 64512
